version: '3'

services:
  emby:
    image: linuxserver/emby:latest
    container_name: emby
    hostname: emby
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./config/emby:/config
      - /mnt/media:/data
    labels:
      # auto update image
      # - "com.centurylinklabs.watchtower.enable=true"
      # traefik
      - "traefik.enable=true"
      # svc
      - "traefik.http.services.emby.loadbalancer.server.port=8096"
      # http
      - "traefik.http.routers.emby.entrypoints=web"
      - "traefik.http.routers.emby.rule=Host(`emby.media.local`)"
      - "traefik.http.routers.emby.service=emby"
    ports:
      - 8096
  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest
    container_name: chinesesubfinder
    hostname: chinesesubfinder
    restart: unless-stopped
    volumes:
      - ./config/chinesesubfinder:/config  # 冒号左边请修改为你想在主机上保存配置、日志等文件的路径
      - /mnt/media:/media    # 请修改为你的媒体目录，冒号右边可以改成你方便记忆的目录，多个媒体目录需要分别映射进来
      - ./config/chinesesubfinder/browser:/root/.cache/rod/browser    # 容器重启后无需再次下载 chrome，除非 go-rod 更新
    environment:
      - PUID=1000         # uid
      - PGID=1000         # gid
      - PERMS=true        # 是否重设/media权限
      - TZ=Asia/Shanghai  # 时区
      - UMASK=022         # 权限掩码
    labels:
      # auto update image
      # - "com.centurylinklabs.watchtower.enable=true"
      # traefik
      - "traefik.enable=true"
      # svc
      - "traefik.http.services.chinesesubfinder.loadbalancer.server.port=19035"
      # http
      - "traefik.http.routers.chinesesubfinder.entrypoints=web"
      - "traefik.http.routers.chinesesubfinder.rule=Host(`chinesesubfinder.media.local`)"
      - "traefik.http.routers.chinesesubfinder.service=chinesesubfinder"
    ports:
      - 19035  # 从0.20.0版本开始，通过webui来设置
      - 19037:19037  # webui 的视频列表读取图片用，务必设置不要暴露到外网
    logging:
        driver: "json-file"
        options:
          max-size: "100m" # 限制docker控制台日志大小，可自行调整
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./config/prowlarr:/config
    labels:
      # auto update image
      # - "com.centurylinklabs.watchtower.enable=true"
      # traefik
      - "traefik.enable=true"
      # svc
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
      # http
      - "traefik.http.routers.prowlarr.entrypoints=web"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.media.local`)"
      - "traefik.http.routers.prowlarr.service=prowlarr"
    ports:
      - 9696
  ombi:
    image: linuxserver/ombi:latest
    container_name: ombi
    hostname: ombi
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./config/ombi:/config
    labels:
      # auto update image
      # - "com.centurylinklabs.watchtower.enable=true"
      # traefik
      - "traefik.enable=true"
      # svc
      - "traefik.http.services.ombi.loadbalancer.server.port=3579"
      # http
      - "traefik.http.routers.ombi.entrypoints=web"
      - "traefik.http.routers.ombi.rule=Host(`ombi.media.local`)"
      - "traefik.http.routers.ombi.service=ombi"
    ports:
      - 3579
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./config/sonarr:/config
      - /mnt/media:/data
    labels:
      # auto update image
      # - "com.centurylinklabs.watchtower.enable=true"
      # traefik
      - "traefik.enable=true"
      # svc
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      # http
      - "traefik.http.routers.sonarr.entrypoints=web"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.media.local`)"
      - "traefik.http.routers.sonarr.service=sonarr"
    ports:
      - 8989
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./config/radarr:/config
      - /mnt/media:/data
    labels:
      # auto update image
      # - "com.centurylinklabs.watchtower.enable=true"
      # traefik
      - "traefik.enable=true"
      # svc
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      # http
      - "traefik.http.routers.radarr.entrypoints=web"
      - "traefik.http.routers.radarr.rule=Host(`radarr.media.local`)"
      - "traefik.http.routers.radarr.service=radarr"
    ports:
      - 7878
  qbittorrent:
    image: superng6/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./config/qbittorrent:/config
      - /mnt/media:/data
    labels:
      # auto update image
      # - "com.centurylinklabs.watchtower.enable=true"
      # traefik
      - "traefik.enable=true"
      # svc
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
      # http
      - "traefik.http.routers.qbittorrent.entrypoints=web"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.media.local`)"
      - "traefik.http.routers.qbittorrent.service=qbittorrent"
    ports:
      - 8080
      - 26881:26881/tcp
      - 26881:26881/udp
  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    hostname: flaresolverr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TEST_URL=http://www.baidu.com
      - TZ=Asia/Shanghai
    labels:
      # auto update image
      # - "com.centurylinklabs.watchtower.enable=true"
      # traefik
      - "traefik.enable=true"
      # svc
      - "traefik.http.services.flaresolverr.loadbalancer.server.port=8191"
      # http
      - "traefik.http.routers.flaresolverr.entrypoints=web"
      - "traefik.http.routers.flaresolverr.rule=Host(`flaresolverr.media.local`)"
      - "traefik.http.routers.flaresolverr.service=flaresolverr"
    ports:
      - 8191


networks:
  default:
    name: traefik_bridge
    external: true